Repository One-Hundred-Trials/Good-Harvest-Market, pull requests merged in 2022-12, with the labels that each got.

#9 Style : Button 컴포넌트 UI 제작
  src/components/Button/Button.jsx
Labels: UI

#10 Style : Product 컴포넌트 UI 제작
  src/components/Product/Product.jsx
Labels: UI

#11 Style: Comment 작성 컴포넌트 UI 제작
  src/components/Comment/CommentInput/CommentInput.jsx
Labels: UI

#14 Style: Profile_component UI 제작
  src/components/Follow/Follow.jsx
  src/components/Follow/FollowStyle.jsx
  src/components/FollowersCount/FollowersCount.jsx
  src/components/FollowersCount/FollowersCountStyle.jsx
  src/components/FollowingsCount/FollowingsCount.jsx
  src/components/FollowingsCount/FollowingsCountStyle.jsx
  src/components/Profile/Profile.jsx
  src/components/Profile/ProfileStyle.jsx
  src/components/ProfileAccount/ProfileAccount.jsx
  src/components/ProfileAccount/ProfileAccountStyle.jsx
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImgStyle.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
Labels: UI

#18 Style : modal alert 컴포넌트 UI
  src/components/Header/Header.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/ModalAlert/ModalAlert.jsx
Labels: UI

#13 Style: Profile_component UI 제작
  src/components/Header/Header.jsx
Labels: UI

#15 Modify : Comment Input 스타일 컴포넌트 파일 분리
  src/components/Comment/CommentInput/CommentInput.jsx
  src/components/Comment/CommentInput/CommentInputStyle.jsx
Labels: modify

#17 Style : Nav 컴포넌트 UI 제작
  src/components/Nav/Nav.jsx
  src/components/Nav/NavItem.jsx
  src/components/Nav/NavItemStyle.jsx
  src/components/Nav/NavStyle.jsx
Labels: UI

#16 Style : Modal Slide 컴포넌트 UI 제작
  src/components/Modal/ModalSlide.jsx
  src/components/Modal/ModalSlideStyle.jsx
Labels: UI

#29 Style : ProfileImgAccountStyle component 제작
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
  src/components/ProfileImgAccount/ProfileImgAccountStyle.jsx
Labels: UI

#31 Style : Header Component UI 제작
  src/components/Header/Header.jsx
  src/components/Header/TopBasicNav/TopBasicNav.jsx
  src/components/Header/TopBasicNav/TopBasicNavStyle.jsx
  src/components/Header/TopChatNav/TopChatNav.jsx
  src/components/Header/TopChatNav/TopChatNavStyle.jsx
  src/components/Header/TopMainNav/TopMainNav.jsx
  src/components/Header/TopMainNav/TopMainNavStyle.jsx
  src/components/Header/TopSearchNav/TopSearchNav.jsx
  src/components/Header/TopSearchNav/TopSearchNavStyle.jsx
  src/components/Header/TopUploadNav/TopUploadNav.jsx
  src/components/Header/TopUploadNav/TopUploadNavStyle.jsx
Labels: UI

#37 Style : LoginEmail Page UI 제작
  src/components/Button/Button.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmailStyle.jsx
Labels: UI

#40 Style : Input Component UI 제작
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.jsx
Labels: UI

#41 Modify : Input.jsx에서 style 파일 분리
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.jsx
Labels: modify

#23 Style : 404페이지 UI 제작
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/NotFoundStyle.jsx
Labels: UI

#32 Style : Followers/Following page
  src/components/FollowUserList/FollowUserList.jsx
  src/components/FollowUserList/FollowUserListStyle.jsx
  src/pages/Main/Profile/MyProfile/FollowList/FollowList.jsx
Labels: UI

#38 Style : ProductList 컴포넌트 UI 제작
  src/components/ProductList/ProductList.jsx
  src/components/ProductList/ProductListStyle.jsx
Labels: UI

#42 Modify : Input Component 스타일 변경
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.jsx
Labels: modify

#44 Modify : Input 스타일 변경
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.jsx
Labels: modify

#36 Style : Login Page UI 제작
  src/pages/Login/Login.jsx
  src/pages/Login/LoginStyle.jsx
Labels: UI, modify

#48 Modify : Header Component UI
  src/components/Button/Button.jsx
  src/components/Header/TopUploadNav/TopUploadNav.jsx
Labels: UI, modify

#49 Style/product upload edit page
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.jsx
  src/components/ProductImgUpload/ProductImgUpload.jsx
  src/components/ProductImgUpload/ProductImgUploadStyle.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUploadStyle.jsx
  src/styles/GlobalStyles.jsx
Labels: UI, modify

#51 Style : Home pages UI 제작 및 Blank component 제작
  src/assets/img/duck-blank.png
  src/components/Blank/Blank.jsx
  src/components/Blank/BlankStyle.jsx
  src/components/HomeRender/HomeRenderBlank.jsx
  src/components/HomeRender/HomeRenderHomeFeed.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/NotFoundStyle.jsx
Labels: UI, modify

#57 Style : ChatList, ChatRoom 컴포넌트 및 페이지 UI 제작
  src/assets/img/chat-send.png
  src/components/Button/UploadFileBtn/UploadFileBtn.jsx
  src/components/Button/UploadFileBtn/UploadFileBtnStyle.jsx
  src/components/Chat/ChatList/ChatList.jsx
  src/components/Chat/ChatList/ChatListStyle.jsx
  src/components/Chat/ChatRoom/ChatComment/ChatComment.jsx
  src/components/Chat/ChatRoom/ChatComment/ChatCommentStyle.jsx
  src/components/Chat/ChatRoom/ChatItem/ChatItem.jsx
  src/components/Chat/ChatRoom/ChatItem/ChatItemStyle.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoomStyle.jsx
Labels: UI

#60 Style : PostUpload 페이지 UI 제작
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
Labels: UI

#52 Style : UserProfile Page UI 제작
  src/assets/img/iccon-img-layers.png
  src/assets/img/unsplash_5MF7EFgy02U.png
  src/components/AlbumIcon/AlbumIcon.jsx
  src/components/ChatIcon/ChatIcon.jsx
  src/components/FollowersCount/FollowersCount.jsx
  src/components/FollowersCount/FollowersCountStyle.jsx
  src/components/FollowingsCount/FollowingsCount.jsx
  src/components/FollowingsCount/FollowingsCountStyle.jsx
  src/components/ListIcon/ListIcon.jsx
  src/components/ListOrAlbum/ListOrAlbum.jsx
  src/components/PostAlbum/PostAlbum.jsx
  src/components/PostAlbumList/PostAlbumList.jsx
  src/components/PostCarList/PostCardList.jsx
  src/components/PostCard/PostCard.jsx
  src/components/ProductList/ProductListStyle.jsx
  src/components/Profile/Profile.jsx
  src/components/Profile/ProfileStyle.jsx
  src/components/ProfileAccount/ProfileAccount.jsx
  src/components/ShareIcon/ShareIcon.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
  src/styles/GlobalStyles.jsx
Labels: UI

#55 Style : Profile Edit Page UI 제작
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEditStyle.jsx
  src/styles/GlobalStyles.jsx
Labels: UI

#62 Style : Post page UI 제작
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentStyle.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/CommentInputStyle.jsx
  src/pages/Main/Post/Post.jsx
Labels: UI

#63 Feat: Router 기능 구현
  src/App.jsx
  src/components/Nav/Nav.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmailStyle.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
  src/pages/Root.jsx
  src/pages/Signup/Signup.jsx
Labels: feat, modify

#64 Modify : module not found 에러 해결
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmailStyle.jsx
  src/pages/Login/LoginStyle.jsx
Labels: modify

#76 Modify : Header Component UI 수정
  .eslintrc.js
  src/components/Header/Header.jsx
  src/components/Header/HeaderStyle.jsx
  src/components/Header/TopBasicNav/TopBasicNav.jsx
  src/components/Header/TopBasicNav/TopBasicNavStyle.jsx
  src/components/Header/TopChatNav/TopChatNav.jsx
  src/components/Header/TopChatNav/TopChatNavStyle.jsx
  src/components/Header/TopMainNav/TopMainNav.jsx
  src/components/Header/TopMainNav/TopMainNavStyle.jsx
  src/components/Header/TopSearchNav/TopSearchNav.jsx
  src/components/Header/TopUploadNav/TopUploadNav.jsx
  src/components/Header/TopUploadNav/TopUploadNavStyle.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Profile/MyProfile/FollowList/FollowList.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: UI, modify

#68 Style : 페이지 컨테이너 레이아웃 수정
  src/App.jsx
  src/components/Chat/ChatListItem/ChatListItem.jsx
  src/components/Chat/ChatListItem/ChatListItemStyle.jsx
  src/components/HomeRender/HomeRenderBlank.jsx
  src/components/HomeRender/HomeRenderHomeFeed.jsx
  src/components/PostCard/PostCardStyle.jsx
  src/components/PostCardList/PostCardList.jsx
  src/components/Product/ProductStyle.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoomStyle.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
  src/pages/Main/Profile/MyProfile/FollowList/FollowList.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/Product/Product.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUploadStyle.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
  src/pages/Root.jsx
  src/pages/Splash/Splash.jsx
  src/pages/Splash/SplashStyle.jsx
  src/styles/GlobalStyles.jsx
Labels: UI, modify

#70 Modify : 전반적 컴포넌트 리팩토링
  src/components/Button/UploadFileBtn/UploadFileBtn.jsx
  src/components/Button/UploadFileBtn/UploadFileBtnStyle.jsx
  src/components/Chat/ChatList/ChatList.jsx
  src/components/Chat/ChatList/ChatListStyle.jsx
  src/components/Chat/ChatRoom/ChatComment/ChatCommentStyle.jsx
  src/components/Chat/ChatRoom/ChatItem/ChatItemStyle.jsx
  src/components/ChatIcon/ChatIcon.jsx
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentStyle.jsx
  src/components/Follow/FollowStyle.jsx
  src/components/FollowUserList/FollowUserList.jsx
  src/components/FollowUserList/FollowUserListStyle.jsx
  src/components/HomeRender/HomeRenderHomeFeed.jsx
  src/components/ListOrAlbum/ListOrAlbum.jsx
  src/components/Nav/NavStyle.jsx
  src/components/PostAlbum/PostAlbum.jsx
  src/components/PostCarList/PostCardList.jsx
  src/components/PostCard/PostCard.jsx
  src/components/Product/Product.jsx
  src/components/ProductImgUpload/ProductImgUpload.jsx
  src/components/ProductImgUpload/ProductImgUploadStyle.jsx
  src/components/Profile/Profile.jsx
  src/components/Profile/ProfileStyle.jsx
  src/components/ProfileAccount/ProfileAccount.jsx
  src/components/ProfileAccount/ProfileAccountStyle.jsx
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
Labels: UI, modify

#78 Modify : 페이지의 header 컴포넌트 링크 업데이트
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
Labels: UI

#79 Style/input file component UI
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImgStyle.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEditStyle.jsx
  src/pages/Signup/SignupUserProfile.jsx
  src/pages/Signup/SignupUserProfileStyle.jsx
Labels: UI, modify

#83 Feat: Login 기능 구현
  package-lock.json
  package.json
  public/data/login.json
  src/_state/auth.js
  src/components/Button/Button.jsx
  src/components/Input/Input.jsx
  src/index.js
  src/pages/Login/Login.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginEmail/LoginEmailStyle.jsx
  src/pages/Login/LoginStyle.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Root.jsx
Labels: UI, feat

#84 Modify: login 기능 수정
  src/_state/auth.js
  src/api/api.js
  src/components/Nav/NavItem.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Root.jsx
Labels: feat, modify

#87 Style/profile component modify
  src/components/Chat/ChatListItem/ChatListItem.jsx
  src/components/Profile/Profile.jsx
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImgStyle.jsx
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
  src/components/UploadProfileImg/UploadProfileImg.jsx
  src/components/UploadProfileImg/UploadProfileImgStyle.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
Labels: UI, modify

#89 Feat/sign up page form validation
  package-lock.json
  package.json
  src/App.jsx
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.jsx
  src/pages/Signup/Register.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupUserProfile.jsx
Labels: UI

#88 Feat : Home feed post list Read
  src/API.jsx
  src/components/CommentsIcon/CommentIcon.jsx
  src/components/HearIcon/HeartIcon.jsx
  src/components/HomeRender/HomeRenderHomeFeed.jsx
  src/components/Nav/NavItem.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCardList/PostCardList.jsx
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
  src/pages/Main/Home/Home.jsx
Labels: feat

#93 Feat: PostUpload 게시글 작성 페이지 구현
  src/components/Button/Button.jsx
  src/components/Button/UploadFileBtn/UploadFileBtn.jsx
  src/components/Header/Header.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
Labels: feat

#94 Modify : Button 에러 해결
  src/components/Button/Button.jsx
  src/components/PostCardList/PostCardList.jsx
  src/pages/Main/Home/Home.jsx
Labels: modify

#97 Feat : Profile Page 내 게시글 및 프로필 보여주기 기능
  src/App.jsx
  src/components/FollowersCount/FollowersCount.jsx
  src/components/Nav/Nav.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCardList/PostCardList.jsx
  src/components/Profile/Profile.jsx
  src/components/ProfileAccount/ProfileAccount.jsx
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: UI, feat, modify

#98 Modify : ProfileImgAccount 컴포넌트 주석처리
  src/components/Chat/ChatListItem/ChatListItem.jsx
Labels: modify

#92 Feat : login validation
  src/pages/Login/LoginEmail/LoginEmail.jsx
Labels: feat, modify

#95 Feat : 회원가입 폼 유효성 검증 기능 구현
  .eslintrc.js
  src/components/UploadProfileImg/UploadProfileImg.jsx
  src/components/UploadProfileImg/UploadProfileImgStyle.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupStyle.jsx
  src/pages/Signup/SignupUserProfile.jsx
  src/pages/Signup/SignupUserProfileStyle.jsx
Labels: feat

#99 Feat : Product 등록 구현
  src/components/Button/Button.jsx
  src/components/Button/UploadFileBtn/UploadFileBtn.jsx
  src/components/Header/Header.jsx
  src/components/Input/Input.jsx
  src/components/ProductImgUpload/ProductImgUpload.jsx
  src/components/ProductImgUpload/ProductImgUploadStyle.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUploadStyle.jsx
Labels: feat

#107 Feat : PostUpload 이미지 여러장 미리보기 및 삭제 기능
  src/components/Button/UploadFileBtn/UploadFileBtn.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
Labels: feat

#111 Feat : my_profile 페이지에 product list 불러오는 기능 추가
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: feat

#114 Feat : Product Modal Alert 구현
  src/components/Modal/LoginModalAlert/LoginAlert.jsx
  src/components/Modal/LoginModalAlert/LoginModal.jsx
  src/components/Modal/LoginModalAlert/LoginModalStyle.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/PostModalAlert/PostAlert.jsx
  src/components/Modal/PostModalAlert/PostModal.jsx
  src/components/Modal/PostModalAlert/PostModalStyle.jsx
  src/components/Modal/ProductModalAlert/ProductAlert.jsx
  src/components/Modal/ProductModalAlert/ProductAlertStyle.jsx
  src/components/Modal/ProductModalAlert/ProductModal.jsx
  src/components/Modal/ProductModalAlert/ProductModalStyle.jsx
  src/components/Product/Product.jsx
Labels: UI, feat, modify

#112 Feat : Profile Edit Page Read
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
Labels: feat

#116 Feat : Profile 페이지 게시글 album 형으로 보여주기
  src/components/PostAlbum/PostAlbum.jsx
  src/components/PostAlbumList/PostAlbumList.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: feat

#117 Feat : Profile Edit Page Update
  src/components/Input/Input.jsx
  src/components/UploadProfileImg/UploadProfileImg.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
Labels: feat

#122 Modify : Profile Edit Page Read
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
Labels: feat

#125 Feat : Post 수정 페이지 구현
  src/App.jsx
  src/components/Header/Header.jsx
  src/pages/Main/Post/PostEdit/PostEdit.jsx
Labels: feat

#127 Feat : post 상세 페이지 구현
  src/components/CommentInput/CommentInputStyle.jsx
  src/components/CommentsIcon/CommentIcon.jsx
  src/components/CommentsIcon/CommentIconStyle.jsx
  src/components/PostCard/PostCard.jsx
  src/pages/Main/Post/Post.jsx
Labels: feat

#121 Feat : 상품 삭제 구현
  src/components/Modal/ProductModalAlert/ProductAlert.jsx
  src/components/Modal/ProductModalAlert/ProductModal.jsx
Labels: feat

#131 Feat: 홈 피드 무한 스크롤 구현
  src/pages/Main/Home/Home.jsx
Labels: feat

#132 Feat/logout
  src/components/Header/Header.jsx
  src/components/Header/HeaderStyle.jsx
  src/components/Modal/LoginModalAlert/LoginAlert.jsx
  src/components/Modal/LoginModalAlert/LoginModal.jsx
  src/components/Modal/LoginModalAlert/LoginModalStyle.jsx
Labels: feat

#123 Feat : Splash 화면 구현
  package-lock.json
  package.json
  src/assets/img/intro-logo-bg.png
  src/assets/img/intro-logo-leaf.png
  src/assets/img/intro-logo-text.png
  src/pages/Login/Login.jsx
  src/pages/Root.jsx
  src/pages/Splash/Splash.jsx
  src/pages/Splash/SplashStyle.jsx
Labels: feat, style, modify

#135 Feat : 게시글 상세 페이지 댓글 구현
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentStyle.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/CommentInputStyle.jsx
  src/components/Modal/CommentModel/CommentAlert.jsx
  src/components/Modal/CommentModel/CommentAlertStyle.jsx
  src/components/Modal/CommentModel/CommentModal.jsx
  src/components/Modal/CommentModel/CommentModalStyle.jsx
  src/components/PostTxt/PostTxt.jsx
  src/pages/Main/Post/Post.jsx
Labels: feat

#138 Modify/login
  src/components/Nav/Nav.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
Labels: feat, modify

#140 Modify : Myprofile_Page 및 UserProfile_Page 수정 및 보완
  src/components/ChatIcon/ChatIcon.jsx
  src/components/PostAlbumList/PostAlbumList.jsx
  src/components/Profile/Profile.jsx
  src/components/ShareIcon/ShareIcon.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: UI, feat, modify

#142 Modify : Nav 수정
  src/components/Nav/Nav.jsx
  src/components/Nav/NavItem.jsx
Labels: UI, modify

#143 Feat : Chat, ChatRoom 페이지 구현
  src/components/Chat/ChatListItem/ChatListItem.jsx
  src/components/Chat/ChatRoom/ChatComment/ChatComment.jsx
  src/components/Chat/ChatRoom/ChatItem/ChatItem.jsx
  src/components/ChatCommentInput/ChatCommentInput.jsx
  src/components/ChatCommentInput/ChatCommentInputStyle.jsx
  src/components/ChatItem/ChatItem.jsx
  src/components/ChatItem/ChatItemStyle.jsx
  src/components/ChatListItem/ChatListItem.jsx
  src/components/ChatListItem/ChatListItemStyle.jsx
  src/components/CommentInput/CommentInputStyle.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoomStyle.jsx
Labels: UI, feat
