Repository One-Hundred-Trials/Good-Harvest-Market, pull requests merged in 2023-02, with the labels that each got.

#201 Refactor : Home 페이지 getFollowFeed api 정리
  src/api/Feed/getFollowFeed.js
  src/pages/Main/Home/Home.jsx
Labels: modify

#208 Modify : 게시물 기존 이미지 업로드 및 게시글 삭제 코드 수정
  src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx
  src/pages/Main/Post/PostEdit/PostEdit.jsx
Labels: modify

#205 Feat/Favicon 설정
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
  public/full-logo.png
  public/index.html
Labels: feat

#221 Refactor : 내 프로필 팔로잉 버튼 hidden 처리
  src/components/FollowUserList/FollowUserList.jsx
  src/components/common/ProfileImgAccount/ProfileImgAccount.jsx
Labels: UI, refactor

#220 Refactor : section에 heading tag 작성
  src/components/PostAlbum/PostAlbum.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginStyle.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoomStyle.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
  src/pages/NotFound/NotFound.jsx
Labels: refactor

#219 Refactor: 팔로우 버튼 클릭 시 팔로워 수 새로고침 안되는 문제 해결
  src/api/Profile/getUserFollowerList.js
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: bug, refactor

#209 Modify : Font 전역 설졍
  src/App.jsx
  src/assets/fonts/SpoqaHanSansNeo/LICENSE
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoBold.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoBold.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoBold.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoMedium.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoMedium.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoMedium.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoRegular.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoRegular.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeoRegular.woff2
  src/styles/GlobalStyles.jsx
  src/styles/font.css
Labels: bug, modify

#217 Refactor/split files
  src/components/AlbumIcon/AlbumIcon.jsx
  src/components/AlbumIcon/AlbumIconStyle.jsx
  src/components/ChatIcon/ChatIcon.jsx
  src/components/ChatIcon/ChatIconStyle.jsx
  src/components/HomeRender/HomeRenderBlank.jsx
  src/components/HomeRender/HomeRenderStyle.jsx
  src/components/ListIcon/ListIcon.jsx
  src/components/ListIcon/ListIconStyle.jsx
  src/components/ListOrAlbum/ListOrAlbum.jsx
  src/components/ListOrAlbum/ListOrAlbumStyle.jsx
  src/components/PostAlbum/PostAlbum.jsx
  src/components/PostAlbum/PostAlbumStyle.jsx
  src/components/PostAlbumList/PostAlbumList.jsx
  src/components/PostAlbumList/PostAlbumListStyle.jsx
  src/components/PostCardList/PostCardList.jsx
  src/components/PostCardList/PostCardListStyle.jsx
  src/components/ShareIcon/ShareIcon.jsx
  src/components/ShareIcon/ShareIconStyle.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Button/ButtonStyle.jsx
  src/components/common/Modal/LoginModalAlert/LoginAlert.jsx
  src/components/common/Modal/LoginModalAlert/LoginAlertStyle.jsx
  src/components/common/Nav/NavItemStyle.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatStyle.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/HomeStyle.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Home/Search/SearchStyle.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/NotFoundStyle.jsx
  src/pages/Root.jsx
  src/pages/RootStyle.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupStyle.jsx
  src/pages/Signup/SignupUserProfile.jsx
  src/pages/Signup/SignupUserProfileStyle.jsx
Labels: refactor

#215 Feat/absolute path
  .eslintrc.js
  jsconfig.json
  src/App.jsx
  src/components/AlbumIcon/AlbumIcon.jsx
  src/components/Blank/Blank.jsx
  src/components/Blank/BlankList.jsx
  src/components/ChatIcon/ChatIcon.jsx
  src/components/ChatItem/ChatItem.jsx
  src/components/ChatListItem/ChatListItem.jsx
  src/components/Comment/Comment.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/Follow/Follow.jsx
  src/components/FollowUserList/FollowUserList.jsx
  src/components/HeartIcon/HeartIcon.jsx
  src/components/HomeRender/HomeRenderBlank.jsx
  src/components/ListIcon/ListIcon.jsx
  src/components/PostAlbumList/PostAlbumList.jsx
  src/components/PostCard/PostCard.jsx
  src/components/Product/Product.jsx
  src/components/Profile/Profile.jsx
  src/components/ShareIcon/ShareIcon.jsx
  src/components/UploadProfileImg/UploadProfileImg.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx
  src/components/common/Modal/PostModalAlert/PostModal.jsx
  src/components/common/Modal/PostModalAlert/PostReportAlert.jsx
  src/components/common/Modal/ProductModalAlert/ProductAlert.jsx
  src/components/common/Modal/ProductModalAlert/ProductModal.jsx
  src/components/common/Nav/Nav.jsx
  src/components/common/Nav/NavStyle.jsx
  src/components/common/ProfileImg/ProfileImg.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoomStyle.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostEdit/PostEdit.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Profile/MyProfile/FollowerList/FollowerList.jsx
  src/pages/Main/Profile/MyProfile/FollowingList/FollowingList.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/Root.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupUserProfile.jsx
  src/pages/Splash/Splash.jsx
Labels: refactor

#222 Refactor : 모바일 환경 이미지 크기 수정
  src/components/HeartIcon/HeartIconStyle.jsx
  src/components/common/Header/Header.jsx
Labels: refactor

#224 Refactor/mobile mode
  src/components/FollowUserList/FollowUserList.jsx
  src/components/HeartIcon/HeartIconStyle.jsx
  src/components/common/Button/ButtonStyle.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
Labels: UI, refactor

#228 Refactor : 모달 알림창 분리
  src/components/Comment/Comment.jsx
  src/components/PostCard/PostCard.jsx
  src/components/Product/Product.jsx
  src/components/common/Alert/AlertStyle.jsx
  src/components/common/Alert/CommentAlert.jsx
  src/components/common/Alert/LoginAlert.jsx
  src/components/common/Alert/PostDeleteAlert.jsx
  src/components/common/Alert/PostReportAlert.jsx
  src/components/common/Alert/ProductAlert.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Modal/CommentModal.jsx
  src/components/common/Modal/LoginModal.jsx
  src/components/common/Modal/LoginModalAlert/LoginAlertStyle.jsx
  src/components/common/Modal/LoginModalAlert/LoginModalStyle.jsx
  src/components/common/Modal/ModalStyle.jsx
  src/components/common/Modal/PostModal.jsx
  src/components/common/Modal/PostModalAlert/PostAlertStyle.jsx
  src/components/common/Modal/PostModalAlert/PostModalStyle.jsx
  src/components/common/Modal/PostReportModal.jsx
  src/components/common/Modal/ProductModal.jsx
  src/components/common/Modal/ProductModalAlert/ProductAlertStyle.jsx
  src/components/common/Modal/ProductModalAlert/ProductModalStyle.jsx
Labels: refactor

#223 Feat/react-helmet-async을 사용한 타이틀 설정
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/components/MetaDatas/MetaDatas.jsx
  src/index.js
  src/pages/Loading/Loading.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostEdit/PostEdit.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Profile/MyProfile/FollowerList/FollowerList.jsx
  src/pages/Main/Profile/MyProfile/FollowingList/FollowingList.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
  src/pages/Main/Profile/UserProfile/FollowList/FollowList.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupStyle.jsx
  src/pages/Signup/SignupUserProfile.jsx
  src/pages/Signup/SignupUserProfileStyle.jsx
  src/pages/Splash/Splash.jsx
Labels: feat

#230 LightHouse 점수 개선을 위한 코드 수정
  src/components/Blank/Blank.jsx
  src/components/CommentsIcon/CommentIcon.jsx
  src/components/MetaDatas/MetaDatas.jsx
  src/components/PostCard/PostCard.jsx
  src/components/Product/ProductStyle.jsx
  src/components/common/Nav/Nav.jsx
Labels: modify

#231 Modify : Error resolving
  .eslintrc.js
  src/components/ShareIcon/ShareIcon.jsx
  src/pages/Login/Login.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
  src/pages/NotFound/NotFound.jsx
Labels: bug, modify

#235 Modify : react-snap과 hydration 제거
  package-lock.json
  package.json
  src/index.js
Labels: bug, modify

#237 Modify : common 폴더명 수정
  src/components/Common/Alert/AlertStyle.jsx
  src/components/Common/Alert/CommentAlert.jsx
  src/components/Common/Alert/LoginAlert.jsx
  src/components/Common/Alert/PostDeleteAlert.jsx
  src/components/Common/Alert/PostReportAlert.jsx
  src/components/Common/Alert/ProductAlert.jsx
  src/components/Common/Button/Button.jsx
  src/components/Common/Button/ButtonStyle.jsx
  src/components/Common/Header/Header.jsx
  src/components/Common/Header/HeaderStyle.jsx
  src/components/Common/Input/Input.jsx
  src/components/Common/Input/InputStyle.jsx
  src/components/Common/Modal/CommentModal.jsx
  src/components/Common/Modal/LoginModal.jsx
  src/components/Common/Modal/LoginModalAlert/LoginAlert.jsx
  src/components/Common/Modal/LoginModalAlert/LoginAlertStyle.jsx
  src/components/Common/Modal/ModalStyle.jsx
  src/components/Common/Modal/PostModal.jsx
  src/components/Common/Modal/PostReportModal.jsx
  src/components/Common/Modal/ProductModal.jsx
  src/components/Common/Nav/Nav.jsx
  src/components/Common/Nav/NavStyle.jsx
  src/components/Common/ProfileAccount/ProfileAccount.jsx
  src/components/Common/ProfileAccount/ProfileAccountStyle.jsx
  src/components/Common/ProfileImg/ProfileImg.jsx
  src/components/Common/ProfileImg/ProfileImgStyle.jsx
  src/components/Common/ProfileImgAccount/ProfileImgAccount.jsx
  src/components/Common/ProfileImgAccount/ProfileImgAccountStyle.jsx
  src/components/Common/UploadFileBtn/UploadFileBtn.jsx
  src/components/Common/UploadFileBtn/UploadFileBtnStyle.jsx
Labels: bug, modify
