Repository One-Hundred-Trials/Good-Harvest-Market, pull requests merged in 2023-01, with the labels that each got.

#109 Feat : Search 페이지 사용자 검색 기능 구현
  src/components/Header/Header.jsx
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
  src/pages/Main/Home/Search/Search.jsx
Labels: feat

#145 Modify : Splash 로직 변경 및 애니메이션 추가
  package-lock.json
  package.json
  src/App.jsx
  src/assets/img/intro-logo-bg.png
  src/components/Header/Header.jsx
  src/components/Modal/LoginModalAlert/LoginAlert.jsx
  src/components/Nav/Nav.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Login/LoginStyle.jsx
  src/pages/Root.jsx
  src/pages/Splash/Splash.jsx
  src/pages/Splash/SplashStyle.jsx
  src/styles/GlobalStyles.jsx
Labels: UI, feat, modify

#149 Modify : Product관련 이슈 해결
  src/components/Input/Input.jsx
  src/components/Modal/ProductModalAlert/ProductAlert.jsx
  src/components/Modal/ProductModalAlert/ProductModal.jsx
  src/components/Product/Product.jsx
  src/components/Product/ProductStyle.jsx
  src/components/ProductList/ProductList.jsx
  src/components/ProductList/ProductListStyle.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEditStyle.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUploadStyle.jsx
Labels: UI, feat, modify

#157 Modify : 게시글 업로드시 이미지 미리보기/삭제 오류 해결
  src/assets/img/icon-upload-file-fill.png
  src/assets/img/icon-upload-file.png
  src/components/Button/UploadFileBtn/UploadFileBtn.jsx
  src/components/Button/UploadFileBtn/UploadFileBtnStyle.jsx
  src/components/UploadProfileImg/UploadProfileImgStyle.jsx
  src/pages/Main/Post/PostEdit/PostEdit.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
Labels: bug, feat

#147 Feat : Follower 기능 구현
  src/App.jsx
  src/components/FollowUserList/FollowUserList.jsx
  src/components/FollowUserList/FollowUserListStyle.jsx
  src/components/FollowersCount/FollowersCount.jsx
  src/components/FollowersCount/FollowersCountStyle.jsx
  src/components/Header/Header.jsx
  src/components/Profile/Profile.jsx
  src/components/ProfileImgAccount/ProfileImgAccountStyle.jsx
  src/pages/Main/Profile/FollowerList/FollowerList.jsx
Labels: feat

#148 Feat : Following 기능 구현
  src/App.jsx
  src/components/FollowUserList/FollowUserList.jsx
  src/components/Profile/Profile.jsx
  src/pages/Main/Profile/MyProfile/FollowList/FollowList.jsx
  src/pages/Main/Profile/MyProfile/FollowingList/FollowingList.jsx
Labels: feat

#158 Modify : Post 이미지 에러 해결
  src/components/PostCard/PostCard.jsx
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
Labels: modify

#159 Modify : path 에러 수정
  src/App.jsx
Labels: modify

#162 Modify : PostCard 컴포넌트 수정
  src/components/AlbumIcon/AlbumIcon.jsx
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentStyle.jsx
  src/components/CommentInput/CommentInput.jsx
  src/components/CommentInput/CommentInputStyle.jsx
  src/components/PostAlbumList/PostAlbumList.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCardStyle.jsx
  src/components/PostCardList/PostCardList.jsx
  src/components/Product/ProductStyle.jsx
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImgStyle.jsx
  src/components/ProfileImgAccount/ProfileImgAccount.jsx
  src/styles/GlobalStyles.jsx
Labels: UI, feat, modify

#163 Add : 404페이지, Homefeed 이동 구현
  src/components/Blank/Blank.jsx
  src/components/HomeRender/HomeRenderBlank.jsx
  src/pages/NotFound/NotFound.jsx
Labels: feat

#165 Modify : Home 조건부 렌더링 오류 수정 및 로딩페이지 제작
  src/components/Blank/Blank.jsx
  src/components/HomeRender/HomeRenderBlank.jsx
  src/pages/Loading/Loading.jsx
  src/pages/Loading/LoadingStyle.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Profile/FollowerList/FollowerList.jsx
  src/pages/Main/Profile/MyProfile/FollowingList/FollowingList.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
  src/pages/NotFound/NotFound.jsx
Labels: UI, feat, modify

#166 Modify/signup
  src/components/Input/Input.jsx
  src/components/Input/InputStyle.jsx
  src/pages/Signup/Signup.jsx
Labels: modify

#167 Modify : 프로필에 따른 판매중인 상품 보여주기
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: modify

#168 Modify/user profile
  src/components/UploadProfileImg/UploadProfileImgStyle.jsx
  src/pages/Signup/SignupUserProfile.jsx
Labels: modify

#169 Modify/profile edit
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
Labels: modify

#164 Feat/user profile follow
  src/components/ChatIcon/ChatIcon.jsx
  src/components/ShareIcon/ShareIcon.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
Labels: feat

#171 Modify : follow limit
  src/pages/Main/Profile/FollowerList/FollowerList.jsx
  src/pages/Main/Profile/MyProfile/FollowingList/FollowingList.jsx
Labels: modify

#174 Modify : 폰트 적용 누락 이슈
  src/assets/img/fonts/SpoqaHanSansNeo/LICENSE
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.otf
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff2
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.otf
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff2
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.otf
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff
  src/assets/img/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff2
  src/styles/GlobalStyles.jsx
Labels: UI, modify

#177 Style : 검색 페이지 빈 화면 컴포넌트 제작 및 적용
  src/assets/img/blank-duck.png
  src/assets/img/blank-leaf.png
  src/components/Blank/BlankList.jsx
  src/components/Blank/BlankListStyle.jsx
  src/pages/Main/Home/Search/Search.jsx
Labels: UI

#178 Modify : 폰트 서브셋 경로 수정
  src/assets/fonts/SpoqaHanSansNeo/LICENSE
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Bold.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Medium.woff2
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.otf
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff
  src/assets/fonts/SpoqaHanSansNeo/SpoqaHanSansNeo-Regular.woff2
  src/styles/GlobalStyles.jsx
Labels: modify

#176 Modify : 게시글 신고 후 유저 프로필 이동 에러 해결
  src/components/Modal/PostModalAlert/PostReportAlert.jsx
  src/components/Modal/PostModalAlert/PostReportModal.jsx
  src/components/PostCard/PostCard.jsx
Labels: bug, feat

#175 Modify : 게시글 수정 페이지 기존 이미지 재업로드 오류 해결
  src/pages/Main/Post/PostEdit/PostEdit.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Post/PostUpload/PostUploadStyle.jsx
Labels: bug, feat

#179 Feat : 게시글 좋아요 기능 구현
  src/assets/img/icon-heart-on.png
  src/components/HearIcon/HeartIcon.jsx
  src/components/HeartIcon/HeartIcon.jsx
  src/components/HeartIcon/HeartIconStyle.jsx
  src/components/PostCard/PostCard.jsx
Labels: feat

#181 Refactor/api
  .eslintrc.js
  public/data/login.json
  src/api/Comment/index.js
  src/api/Feed/index.js
  src/api/Follow/index.js
  src/api/ImgUpload/postImage.js
  src/api/Login/index.js
  src/api/Product/index.js
  src/api/Profile/index.js
  src/api/ProfileSetting/index.js
  src/api/Search/index.js
  src/api/SignUp/postUserSignUp.jsx
  src/api/api.js
  src/components/PostCard/PostCard.jsx
  src/pages/Signup/Signup.jsx
Labels: modify

#183 Refactor : 게시글 등록, 수정, 삭제 api 분리
  src/api/Feed/createPost.js
  src/api/Feed/index.js
  src/api/Profile/getMyProfile.js
  src/api/api.js
  src/api/deleteAPI.js
  src/api/getAPI.js
  src/api/putAPI.js
  src/components/Modal/PostModalAlert/PostDeleteAlert.jsx
  src/pages/Main/Post/PostEdit/PostEdit.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
Labels: feat

#189 Refactor : Product api 분리
  src/api/Product/deleteProduct.js
  src/api/Product/getProduct.js
  src/api/Product/index.js
  src/api/Product/putProduct.js
  src/api/Product/uploadProduct.js
  src/components/Modal/ProductModalAlert/ProductAlert.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductEdit/ProductEdit.jsx
  src/pages/Main/Profile/MyProfile/Product/ProductUpload/ProductUpload.jsx
Labels: refactor

#190 Refactor : Comments api 분리
  src/api/Comment/deleteComment.js
  src/api/Comment/getComment.js
  src/api/Comment/index.js
  src/api/Comment/postComment.js
  src/api/Comment/reportComment.js
  src/api/Post/getPost.jsx
  src/api/getAPI.js
  src/components/Comment/Comment.jsx
  src/components/CommentInput/CommentInput.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostStyle.jsx
Labels: refactor

#185 Refactor : Login API 분리
  .netlify/state.json
  src/api/Login/index.js
  src/api/Login/postUserLogin.js
  src/pages/Login/LoginEmail/LoginEmail.jsx
Labels: refactor

#184 Refactor : 좋아요 기능, 취소 api 분리
  src/api/Feed/deleteLiked.js
  src/api/Feed/postLiked.js
  src/components/HeartIcon/HeartIcon.jsx
Labels: refactor

#188 Refactor/component
  src/components/Blank/Blank.jsx
  src/components/ChatCommentInput/ChatCommentInput.jsx
  src/components/Comment/Comment.jsx
  src/components/PostCard/PostCard.jsx
  src/components/Product/Product.jsx
  src/components/Profile/Profile.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderStyle.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/InputStyle.jsx
  src/components/common/Modal/CommentModel/CommentAlert.jsx
  src/components/common/Modal/CommentModel/CommentAlertStyle.jsx
  src/components/common/Modal/CommentModel/CommentModal.jsx
  src/components/common/Modal/CommentModel/CommentModalStyle.jsx
  src/components/common/Modal/LoginModalAlert/LoginAlert.jsx
  src/components/common/Modal/LoginModalAlert/LoginModal.jsx
  src/components/common/Modal/LoginModalAlert/LoginModalStyle.jsx
  src/components/common/Modal/PostModalAlert/PostAlertStyle.jsx
  src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx
  src/components/common/Modal/PostModalAlert/PostModal.jsx
  src/components/common/Modal/PostModalAlert/PostModalStyle.jsx
  src/components/common/Modal/PostModalAlert/PostReportAlert.jsx
  src/components/common/Modal/PostModalAlert/PostReportModal.jsx
  src/components/common/Modal/ProductModalAlert/ProductAlert.jsx
  src/components/common/Modal/ProductModalAlert/ProductAlertStyle.jsx
  src/components/common/Modal/ProductModalAlert/ProductModal.jsx
  src/components/common/Modal/ProductModalAlert/ProductModalStyle.jsx
  src/components/common/Nav/Nav.jsx
  src/components/common/Nav/NavItemStyle.jsx
  src/components/common/Nav/NavStyle.jsx
  src/components/common/ProfileAccount/ProfileAccount.jsx
  src/components/common/ProfileAccount/ProfileAccountStyle.jsx
  src/components/common/ProfileImg/ProfileImg.jsx
  src/components/common/ProfileImg/ProfileImgStyle.jsx
  src/components/common/ProfileImgAccount/ProfileImgAccount.jsx
  src/components/common/ProfileImgAccount/ProfileImgAccountStyle.jsx
  src/components/common/UploadFileBtn/UploadFileBtn.jsx
  src/components/common/UploadFileBtn/UploadFileBtnStyle.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginEmail/LoginEmail.jsx
  src/pages/Main/Chat/Chat.jsx
  src/pages/Main/Chat/ChatRoom/ChatRoom.jsx
  src/pages/Main/Home/Home.jsx
  src/pages/Main/Home/Search/Search.jsx
  src/pages/Main/Post/Post.jsx
  src/pages/Main/Post/PostUpload/PostUpload.jsx
  src/pages/Main/Profile/MyProfile/MyProfile.jsx
  src/pages/Main/Profile/MyProfile/ProfileEdit/ProfileEdit.jsx
  src/pages/Main/Profile/UserProfile/UserProfile.jsx
  src/pages/Root.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupUserProfile.jsx
  src/pages/Signup/SignupUserProfileStyle.jsx
Labels: refactor

#199 modify : 공통 getAPI, putAPI, deleteAPI 삭제
  src/api/deleteAPI.js
  src/api/getAPI.js
  src/api/putAPI.js
Labels: modify

#200 Refactor : deletePost api 코드 수정
  src/api/Feed/deletePost.js
  src/components/common/Modal/PostModalAlert/PostDeleteAlert.jsx
Labels: modify
